services: 
  db:
    image: postgres:15
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: fulghost
      POSTGRES_PASSWORD: redracka2*
      POSTGRES_DB: mylogbook
    ports:
      - "5432:5432"
 