### GET from /API/VISITORS
GET http://localhost:9000/api/visitorlogs

### POST to /API/VISITORS
POST http://localhost:9000/api/visitorlogs
content-type: application/json

{
  "name": "Jude Fiifi",
  "organisation": "Get More Money inc",
  "nature": "Test",
  "contact": "0208709187",
  "tag": "2"
}

### DELETE visitor log by ID
DELETE http://localhost:9000/api/visitorlogs/0c912b83-01b8-429c-9b28-12359e52d593